[workspace]
members = [
    "analyzer",
    "container",
    "plc2x",
    "plc2plc",
    "dsl",
    "dsl_macro_derive",
    "parser",
    "problems",
    "sources",
    "test",
    "vm"
]
resolver = "2"

[workspace.package]
edition = "2021"
authors = [ "Garret Fick" ]
license = "MIT"
repository = "https://github.com/ironplc/ironplc"
