[package]
name = "ironplc-container"
description = "Binary container format for IronPLC bytecode files"
version = "0.157.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
